### ISSUE TITLE
Package with cordova for andriod OS

### ISSUE THREAD

**Issue by oyes** [oyes/tailor-notes-ui#13]
Fix the following issues that might arise

- Update this list with issues noticed during application launch
- Fix issues noticed ( if trivial )
- Update this list with issues noticed while using on mobile device
- Fix issues noticed ( if trivial )

**Comment by oyes** [comment]
@TODO

- Increase the font of the Menu icons to enable the app look better on mobile phones
- The header should be bigger
- The Add note icon should be bigger

**Comment by emmatex** [comment]
I resolved
